name: Build and release xvm binaries

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build binary
        run: pyinstaller --onefile --clean src/xvm.py

      - name: Rename binary
        run: mv dist/xvm xvm-linux-x64

      - name: Check if built binary exists
        run: |
          if [ ! -f xvm-linux-x64 ]; then
            echo "❌ Binary not found: xvm-linux-x64"
            exit 1
          fi

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: xvm-linux-x64
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
